// <auto-generated />
namespace DoAnWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update2203 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update2203));
        
        string IMigrationMetadata.Id
        {
            get { return "202303230215302_Update2203"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
