// <auto-generated />
namespace DoAnWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sdhj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sdhj));
        
        string IMigrationMetadata.Id
        {
            get { return "202304240906352_sdhj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
